title: Open Research Tools & Technologies
logo: 
description: "A place to discuss creation and use of Free Libre Open Source Software in any kind of research context such as: science, investigative journalism, activism..."
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal